# Generated by Django 6.1.1 on 2026-09-08 01:28

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reported_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='risk',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Modéré'), ('high', 'Élevé')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='severity',
            field=django_enum.fields.EnumPositiveSmallIntegerField(blank=True, choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute'), (4, 'Critique')], null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', [1, 2, 3, 4]), ('severity__isnull', True), _connector='OR'), name='tasks_Task_severity_Severity'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('risk__in', ['low', 'medium', 'high']), ('risk__isnull', True), _connector='OR'), name='tasks_Task_risk_RiskLevel'),
        ),
    ]
