# Generated by Django 6.1.1 on 2026-09-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_billable',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
