# Generated by Django 6.1.1 on 2026-09-19 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_is_billable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='task_progress_entre_0_et_100'),
        ),
    ]
