# Generated by Django 6.1.1 on 2026-09-19 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_progress_entre_0_et_100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='task_projet_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('actual_end_datetime__isnull', True)), fields=['project'], name='task_en_cours_idx'),
        ),
    ]
