# Generated by Django 6.1.1 on 2026-09-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_projet_statut_idx_task_task_en_cours_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='pk',
            field=models.CompositePrimaryKey('task', 'user', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
    ]
